### PR TITLE
Fixes #4 add ability to specify status code on Redirect Plugin

### LINKED ISSUE #4: Ability to specify response code on controller plugin redirect
- [X ] I was not able to find an [open](https://github.com/zendframework/zend-mvc/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-mvc/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [X ] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

I have changed my routing setup on a production app, and I would like to provide search engines with the information that a new URL format is being used. For this I would like to use code 301 (Permanently Moved) instead of 302 (Found).

### Code to reproduce the issue

In a controller action: 
```php
return $this->redirect()->toUrl('https://github.com'); //, ['statusCode' => 301]);
```

### Expected results

I should be able to specify a statusCode of choosing

### Actual results

The browser receives a 302 response code always.

Thanks for all your support!

---

Originally posted by @jroedel at https://github.com/zendframework/zend-mvc/issues/313

### PR DESCRIPTION
**Pull request by samsonasik**
Signed-off-by: Abdul Malik Ikhsan <samsonasik@gmail.com>

|    Q          |   A
|-------------- | ------
| Documentation | yes
| New Feature   | yes

### Description

Fixes #4 add ability to specify status code on Redirect Plugin

### CODE REVIEW

**Comment by samsonasik** [comment]
travis build green 🎉

**Comment by Xerkus** [comment]
This approach produces side effects as status code persists after the call, I would prefer stateless approach.
Besides, redirect returns response object that implements fluent interface, so it could be achieved currently with:
```
return $this->redirect()->toRoute('login-success')->setStatusCode(301);
```

**Comment by Xerkus** [comment]
@samsonasik I am inclined to reject this change due to stateful side effects.


Would existing interface with Response fluent interface satisfy your needs? It could be added to the docs as a helpful hint.
> ```php
> return $this->redirect()->toRoute('login-success')->setStatusCode(301);
> ```

**Comment by samsonasik** [comment]
Ok, I am closing it.

**Pull request closed without merging**
