### PR TITLE
Apply PHP 7.4 syntax and typed property

### PR DESCRIPTION
**Pull request by samsonasik**
Signed-off-by: Abdul Malik Ikhsan <samsonasik@gmail.com>

|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

Since we use php 7.4 as minimum requirement, I think we can update to use php 7.4 syntax and typed properties (for private property to avoid BC break).

### CODE REVIEW

**Comment by samsonasik** [comment]
phpcs notice is unrelated https://github.com/laminas/laminas-mvc/runs/6730950124?check_suite_focus=true#step:3:263

**Comment by Xerkus** [comment]
@samsonasik it is handled as part of migration to coding standard v2. See #121

**Comment by samsonasik** [comment]
ok 👍 , I can rebase after https://github.com/laminas/laminas-mvc/pull/121 merged

**Comment by Xerkus** [comment]
@samsonasik  Do we allow or recommend arrow syntax? I don't remember TSC discussing it.

**Comment by samsonasik** [comment]
I think that's nice to apply when only 1 return stmt inside.

**Comment by samsonasik** [comment]
I will rebase

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
All green 🎉

**Pull request merged**
