### PR TITLE
Add `ControllerManager::class` as resolvable service

### PR DESCRIPTION
**Pull request by rieschl**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | yes

### Description

As discovered in Slack, it is not possible to get the ControllerManager via its FQCN.
This PR adds the FQCN as canonical name of the service and changes the `'ControllerManager'` service to an alias.

### CODE REVIEW

**Comment by rieschl** [comment]
Would it be okay if I clean up the `ServiceListenerFactory` file in this PR a little bit, i.e. use `::class` notation instead of string, add return types, add some tests to increase coverage....?

**Comment by Ocramius** [comment]
> Would it be okay if I clean up the `ServiceListenerFactory` file in this PR a little bit

IMO separate patch - this one is a feature addition, let's make the next bit independently reviewable

**Comment by rieschl** [comment]
I'm not sure, but I think this should be a minor release? But there's no `3.4.x` branch, yet.

**Review by Ocramius — APPROVED** [review]
LGTM :ship:

**Comment by Ocramius** [comment]
@rieschl oof, indeed, branches being a mess again -.-

**Comment by Ocramius** [comment]
Slipped into `3.3.1`, sorry :(

**Pull request merged**
