### PR TITLE
Drop built-in middleware support in favor of laminas-mvc-middleware

### LINKED ISSUE #1: Package http-interop/http-middleware is abandoned
- [x] I was not able to find an [open](https://github.com/zendframework/zend-mvc/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-mvc/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

The package `http-interop/http-middleware` is abandoned. You'll get this if you install zend-mvc version 3.1.1 with composer:

```
Package http-interop/http-middleware is abandoned, you should avoid using it. Use http-interop/http-server-middleware instead.
```

### Code to reproduce the issue

Run in your favourite terminal:
```
$ composer require zendframework/zend-mvc
```

### Expected results

No warnings are expected.

### Actual results

A warning is displayed that the http-interop/http-middleware is abandoned.

---

Originally posted by @halfpastfouram at https://github.com/zendframework/zend-mvc/issues/316

### PR DESCRIPTION
**Pull request by Xerkus**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | yes
| New Feature   | no
| RFC           | no
| QA            | no

### Description
This PR removes all bits for optional middleware pipe support in favor of using `laminas/laminas-mvc-middleware`

Related to #51 
Depends on #50

### CODE REVIEW

**Review by weierophinney — CHANGES_REQUESTED** [review]
This looks good, and we've discussed it before in the TSC.

My only change request is that you create a migration chapter in the documentation that indicates that the MiddlewareListener has been moved to laminas/laminas-mvc-middleware, and link to that package (preferably to its documentation).

**Comment by Xerkus** [comment]
@weierophinney I restored documentation page about laminas-mvc-middleware that got removed during rebase.

I think it is premature to provide migration documentation however. There are numerous changes that would need to be done to get ready for 4.0.0 which would obsolete the migration guide.
I will open a separate issue about providing migration guide in 3.x

**Comment by Xerkus** [comment]
Issue for migration guide to laminas-mvc-middleware is #120

**Review by weierophinney — APPROVED** [review]
Since there is now an issue to track the middleware changes for migration, I'm :+1:

**Pull request merged**
